inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Exclude:
    - rubocopfiles.gemspec

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
