inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/CombinableLoops:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  AllowComments: true

Style/IfUnlessModifier:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 2

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
