name: automerge

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          - MERGE_METHOD: "rebase"
          - UPDATE_METHOD: "rebase"
