name: Dependabot Merge
on: pull_request_target

env:
  protected_files: Gemfile

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Abort if protected files are changed
        run: git diff --exit-code ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} ${{ env.protected_files }}

      - name: Enable auto-merge
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
